# A collection of deployed agent services on all my servers
services:

  # NOTES -----------------------------------------------------------
  #   Ideally I deploy portainer within this stack configuration,
  #   but due to how it's managed, a shared deployment is more
  #   work than it is worth :(
  # -----------------------------------------------------------------


  # -----------------------------------------------------------------
  # Beszel - https://beszel.dev/guide/agent-installation
  beszel:
    container_name: beszel-agent
    image: henrygd/beszel-agent
    restart: always
    network_mode: host

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/bulk:/extra-filesystems/sdb1:ro
      - /data/beszel/agent:/var/lib/beszel-agent

    environment:
      KEY: $BESZEL_PRIVATE_KEY
  # -----------------------------------------------------------------


  # -----------------------------------------------------------------
  # Watchtower - https://containrrr.dev/watchtower/
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # -----------------------------------------------------------------
