# Web Proxy for Jellyfin
services:

  # -----------------------------------------------------------------
  # Nginx - https://hub.docker.com/_/nginx
  nginx:
    container_name: nginx
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped

    ports:
      - 80:80     # Public HTTP Port
      - 443:443   # Public HTTPS Port
      - 81:81     # Admin Web Port

    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST     : $DB_MYSQL_HOST
      DB_MYSQL_PORT     : $DB_MYSQL_PORT
      DB_MYSQL_USER     : $DB_MYSQL_USER
      DB_MYSQL_PASSWORD : $DB_MYSQL_PASS
      DB_MYSQL_NAME     : $DB_MYSQL_NAME

    volumes:
      - /data/nginx/data:/data
      - /data/nginx/letsencrypt:/etc/letsencrypt
  # -----------------------------------------------------------------
